### PR TITLE
AccessRight: 'open','embargoed', 'restricted','closed'

### PR DESCRIPTION
**Pull request by kikislater**
Add accessRight and dependant (embargoDate, accessConditions) for Zenodo to geoflow

Tested with following drive shit: https://docs.google.com/spreadsheets/d/1wTyq-2sJgdvpTzE4309Lyo1vOac7uIb1dMeHEfKcqbg/edit?usp=sharing
and following json : 
https://github.com/IRDG2OI/geoflow-g2oi/blob/sylvain/Zenodo.json

@juldebar

### CODE REVIEW

**Comment by kikislater** [comment]
Documentation needs to be update !

**Comment by eblondel** [comment]
I would be in favor to use an `embargo` key for the date in `Date` column.

**Comment by eblondel** [comment]
For the documentation of the metadata pivot metadata model it is through a CSV file that list possible keys and mark them if they are used in undelying actions: https://github.com/r-geoflow/geoflow/blob/master/doc/Summary_metadata.csv

**Comment by kikislater** [comment]
Done ! Could you please review it

**Review by eblondel — CHANGES_REQUESTED** [review]
@kikislater the property for entity dates is `dates`, and not `date`

**Review by eblondel — APPROVED** [review]

**Review by eblondel — APPROVED** [review]

**Review by kikislater — COMMENTED** [review]
Fix `entity$date` to `entity$dates`
Sorry for that

**Comment by eblondel** [comment]
@kikislater can you implement a control with proper error log in case embargo date is missing (I assume it's a blocker in Zenodo if we don't specify this date)

**Pull request merged**
